name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js version
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x' # Set the Node.js version to use

      # Install dependencies using Yarn
      - name: Install dependencies
        run: yarn install  

      # Build the NestJS app
      - name: Build NestJS app
        run: yarn build   # Build the NestJS app

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: blackbook-be
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  
          package: .  
